package com.foodsave.backend.domain.enums;

public enum ReservationCancellationReason {
    USER_CHANGED_MIND,
    USER_TOO_FAR,
    USER_WRONG_TIME,
    USER_ORDERED_BY_MISTAKE,
    PARTNER_OUT_OF_STOCK,
    PARTNER_CLOSED,
    PARTNER_CANNOT_PREPARE,
    PARTNER_WRONG_QUANTITY,
    PARTNER_TECHNICAL_ERROR,
    PICKUP_TIME_EXPIRED,
    CUSTOMER_DID_NOT_ARRIVE,
    DUPLICATE_RESERVATION,
    OTHER
}
